# Generated by Django 4.2.1 on 2023-05-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='account',
            field=models.CharField(max_length=30, null='Flase'),
        ),
        migrations.AlterField(
            model_name='users',
            name='created_type',
            field=models.CharField(max_length=20, null='Flase'),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=30, null='Flase'),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='users',
            name='status',
            field=models.CharField(max_length=20, null='Flase'),
        ),
    ]
