# Generated by Django 4.2.1 on 2023-05-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_users_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='created_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('google', 'Google')], max_length=20),
        ),
        migrations.AlterField(
            model_name='users',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('verified', 'Verified'), ('unverified', 'Unverified')], max_length=20),
        ),
    ]
