# Generated by Django 4.2.1 on 2023-05-22 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_users_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='exercise_degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_level', models.TextField()),
                ('factor', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='users',
            name='email',
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.IntegerField(choices=[(1, 1), (2, 2)])),
                ('image', models.TextField(blank=True, null=True)),
                ('exercise_degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.exercise_degree')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users')),
            ],
        ),
    ]
