# Generated by Django 4.2.1 on 2023-05-22 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_exercise_degree_remove_users_email_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='exercise_degree',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='exercise_degree',
        ),
        migrations.DeleteModel(
            name='profile',
        ),
        migrations.DeleteModel(
            name='users',
        ),
    ]
