# Generated by Django 4.2.1 on 2023-05-22 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0009_remove_profile_exercise_degree_remove_profile_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='exercise_degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_level', models.TextField()),
                ('factor', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=30)),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('created_type', models.CharField(choices=[('normal', 'Normal'), ('google', 'Google')], max_length=20)),
                ('status', models.CharField(choices=[('success', 'Success'), ('verified', 'Verified'), ('unverified', 'Unverified')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.IntegerField(choices=[(1, 1), (2, 2)])),
                ('birthday', models.DateField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('image', models.TextField(blank=True, null=True)),
                ('exercise_degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.exercise_degree')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users')),
            ],
        ),
    ]
