# Generated by Django 4.2.1 on 2023-05-23 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='exercise_degree',
            new_name='exercise_degree_id',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='user_id',
        ),
    ]
