# Generated by Django 4.2.1 on 2023-05-24 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_profile_exercise_degree_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='exercise_degree',
        ),
    ]
