# Generated by Django 4.2.1 on 2023-05-24 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_profile_gender_emailverifycode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverifycode',
            name='user_id',
        ),
    ]
