# Generated by Django 4.2.1 on 2023-05-24 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_emailverifycode_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverifycode',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.users'),
            preserve_default=False,
        ),
    ]
