# Generated by Django 4.2.1 on 2023-05-24 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_emailverifycode_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverifycode',
            name='user_id',
        ),
    ]
