# Generated by Django 4.2.1 on 2023-05-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_emailverifycode_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverifycode',
            name='email',
            field=models.EmailField(default='test@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
