# Generated by Django 4.2.1 on 2023-05-26 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_emailverifycode_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailverifycode',
            old_name='user_id',
            new_name='user',
        ),
    ]
