# Generated by Django 4.2.1 on 2023-05-26 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_id',
            new_name='user',
        ),
    ]
