# Generated by Django 4.2.2 on 2023-07-05 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfood',
            name='carb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customfood',
            name='fat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customfood',
            name='protein',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customfood',
            name='size',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customfood',
            name='sodium',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customfood',
            name='unit',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
