# Generated by Django 4.2.2 on 2023-07-05 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_customfood_carb_alter_customfood_fat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfood',
            name='store',
            field=models.ForeignKey(default=1, on_delete=models.SET(''), to='api.store'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dietrecord',
            name='label',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dietrecorditem',
            name='carb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dietrecorditem',
            name='fat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dietrecorditem',
            name='protein',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dietrecorditem',
            name='size',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dietrecorditem',
            name='sodium',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dietrecorditem',
            name='unit',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='sport',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sportgroupitem',
            name='custom_counts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sportrecord',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sportrecorditem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sportrecorditem',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='record_video'),
        ),
    ]
