# Generated by Django 4.2.2 on 2023-07-05 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_customfood_store_alter_dietrecord_label_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customfood',
            old_name='food_type',
            new_name='food_type_id',
        ),
        migrations.RenameField(
            model_name='customfood',
            old_name='store',
            new_name='store_id',
        ),
        migrations.RenameField(
            model_name='customfood',
            old_name='user',
            new_name='user_id',
        ),
    ]
