# Generated by Django 4.2.2 on 2023-07-11 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_rename_food_dietrecord_food_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dietrecord',
            old_name='food_id',
            new_name='dietRecordItem_id',
        ),
    ]
