# Generated by Django 4.2.2 on 2023-07-11 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_rename_food_id_dietrecord_dietrecorditem_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='carb',
        ),
        migrations.RemoveField(
            model_name='food',
            name='fat',
        ),
        migrations.RemoveField(
            model_name='food',
            name='food_type_id',
        ),
        migrations.RemoveField(
            model_name='food',
            name='protein',
        ),
        migrations.RemoveField(
            model_name='food',
            name='size',
        ),
        migrations.RemoveField(
            model_name='food',
            name='sodium',
        ),
        migrations.RemoveField(
            model_name='food',
            name='store_id',
        ),
        migrations.RemoveField(
            model_name='food',
            name='unit',
        ),
    ]
