# Generated by Django 4.2.2 on 2023-07-11 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_food_carb_food_fat_food_food_type_id_food_protein_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='name',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
