# Generated by Django 4.2.2 on 2023-07-12 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_rename_time_dietrecord_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietrecord',
            name='modify',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dietrecord',
            name='serving_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='modify',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DailyBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users')),
            ],
        ),
    ]
