# Generated by Django 4.2.2 on 2023-07-15 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_alter_dailybonus_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sportrecorditem',
            old_name='default_time',
            new_name='custom_time',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='animation',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='image',
        ),
        migrations.RemoveField(
            model_name='sportrecorditem',
            name='animation',
        ),
        migrations.RemoveField(
            model_name='sportrecorditem',
            name='image',
        ),
        migrations.AddField(
            model_name='sportgroupitem',
            name='no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sportrecord',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sportrecorditem',
            name='no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='member_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('premium', 'Premium')], default='normal', max_length=10),
        ),
        migrations.AlterField(
            model_name='sportgroupitem',
            name='custom_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sportgroupitem',
            name='mode',
            field=models.CharField(choices=[('timing', '計時'), ('counting', '計次'), ('none', '無限制')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sportrecorditem',
            name='mode',
            field=models.CharField(choices=[('timing', '計時'), ('counting', '計次'), ('none', '無限制')], max_length=20),
        ),
    ]
