# Generated by Django 4.2.2 on 2023-07-20 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_setting_sportrecorditem_custom_counts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportrecord',
            name='rest_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sportrecord',
            name='sport_group_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.sportgroup'),
        ),
    ]
