# Generated by Django 4.2.2 on 2023-07-21 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_sportrecord_rest_time_sportrecord_sport_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportrecord',
            name='cur_sport_no',
            field=models.IntegerField(default=0),
        ),
    ]
