# Generated by Django 4.2.2 on 2023-07-22 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_alter_sportrecord_cur_sport_no'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnimatedCharacter',
            new_name='Animation',
        ),
    ]
