# Generated by Django 4.2.2 on 2023-07-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_alter_setting_alert_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animation',
            name='animation',
            field=models.FileField(blank=True, null=True, upload_to='animation_video'),
        ),
        migrations.AlterField(
            model_name='animation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='animation_img'),
        ),
    ]
