# Generated by Django 4.2.2 on 2023-07-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_alter_animation_animation_alter_animation_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='alert_day',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
