# Generated by Django 4.2.2 on 2023-07-25 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_weigthhistory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WeigthHistory',
            new_name='WeigthtHistory',
        ),
    ]
