# Generated by Django 4.2.2 on 2023-07-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_notificationhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationhistory',
            old_name='crate_at',
            new_name='create_at',
        ),
        migrations.AddField(
            model_name='notificationhistory',
            name='label',
            field=models.TextField(blank=True, null=True),
        ),
    ]
