# Generated by Django 4.2.2 on 2023-08-07 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_rename_crate_at_notificationhistory_create_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='body_fat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='goal',
            field=models.CharField(choices=[('health', '維持身體健康'), ('weight', '減重'), ('fat', '減脂'), ('muscle', '增肌')], default='health', max_length=30),
        ),
    ]
