# Generated by Django 4.2.2 on 2023-08-11 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_alter_waterhistory_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='weight_goal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='type',
            field=models.CharField(default='aerobics', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foodtype',
            name='type',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='sport',
            name='name',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.TextField(unique=True),
        ),
        migrations.CreateModel(
            name='GoalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(choices=[('health', '維持身體健康'), ('weight', '減重'), ('fat', '減脂'), ('muscle', '增肌')], default='health', max_length=30)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users')),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('label', models.CharField(choices=[('common', '共同'), ('sport', '運動'), ('diet', '飲食')], max_length=20)),
                ('is_achieve', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users')),
            ],
        ),
    ]
