# Generated by Django 4.2.2 on 2023-08-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_profile_weight_goal_sport_type_alter_foodtype_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='image',
            field=models.ImageField(default='', upload_to='achievement_img'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
