# Generated by Django 4.2.2 on 2023-08-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_achievement_image_achievement_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='image',
            field=models.FilePathField(default=''),
        ),
    ]
