# Generated by Django 4.2.2 on 2023-08-12 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_alter_achievement_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='is_achieve',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='achievement',
            name='image',
            field=models.ImageField(default='', upload_to='achievement_img'),
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_achieve', models.BooleanField(default=False)),
                ('achievement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.achievement')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users')),
            ],
        ),
    ]
