# Generated by Django 4.2.2 on 2023-08-13 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_remove_achievement_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='no',
        ),
    ]
