# Generated by Django 4.2.2 on 2023-08-13 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_remove_achievement_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAchievement',
        ),
    ]
