# Generated by Django 4.2.2 on 2023-08-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_userachievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='image',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserAchievement',
        ),
    ]
