# Generated by Django 4.2.2 on 2023-08-14 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_userachievement'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietDayRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calorie', models.FloatField(default=0)),
                ('protein', models.FloatField(default=0)),
                ('fat', models.FloatField(default=0)),
                ('carb', models.FloatField(default=0)),
                ('sodium', models.FloatField(default=0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users')),
            ],
        ),
        migrations.CreateModel(
            name='AchievementRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_achieve', models.IntegerField(default=0)),
                ('continuous_bonus', models.IntegerField(default=0)),
                ('continuous_sodium', models.IntegerField(default=0)),
                ('continuous_pfc', models.IntegerField(default=0)),
                ('continuous_calorie', models.IntegerField(default=0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users')),
            ],
        ),
    ]
