# Generated by Django 4.2.2 on 2023-08-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_dietdayrecord_achievementrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievementrecord',
            name='continuous_bonus_state',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='achievementrecord',
            name='count_achieve_state',
            field=models.BooleanField(default=True),
        ),
    ]
