# Generated by Django 4.2.2 on 2023-08-16 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_achievementrecord_continuous_bonus_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dietrecord',
            name='serving_amount',
        ),
    ]
