# Generated by Django 4.2.2 on 2023-08-17 03:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_customfood_modify'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietdayrecord',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
