# Generated by Django 4.2.2 on 2023-08-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_remove_achievementrecord_continuous_calorie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievementrecord',
            name='continuous_protein_state',
            field=models.BooleanField(default=True),
        ),
    ]
