# Generated by Django 4.2.2 on 2023-08-18 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_achievementrecord_continuous_protein_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietrecord',
            name='serving_amount',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
    ]
