# Generated by Django 4.2.2 on 2023-08-19 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_dietrecord_serving_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievementrecord',
            name='sport_all_state',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='achievementrecord',
            name='sport_ten_state',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='achievementrecord',
            name='sport_twenty_state',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='UserAchievedSport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('sport_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sport')),
            ],
        ),
    ]
