# Generated by Django 4.2.2 on 2023-08-19 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_achievementrecord_sport_all_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userachievedsport',
            name='user_id',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='api.users'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userachievedsport',
            name='sport_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.sport'),
        ),
    ]
