# Generated by Django 4.2.2 on 2023-08-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0083_remove_sportrecorditem_custom_counts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportrecorditem',
            name='custom_counts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sportrecorditem',
            name='custom_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
