# Generated by Django 4.2.2 on 2023-08-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0084_sportrecorditem_custom_counts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievementrecord',
            name='continuous_record',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='achievementrecord',
            name='continuous_record_state',
            field=models.BooleanField(default=True),
        ),
    ]
