# Generated by Django 4.2.2 on 2023-08-20 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_dietrecorddate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportRecordWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('seconds', models.FloatField(default=0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users')),
            ],
        ),
        migrations.AddField(
            model_name='achievementrecord',
            name='sport_time_hundredeighty_state',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='achievementrecord',
            name='sport_time_seventyfive_state',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sportrecorditem',
            name='completed_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='DietDayRecord',
        ),
    ]
