# Generated by Django 4.2.2 on 2023-08-20 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0087_sportrecordweek_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SportRecordWeek',
        ),
    ]
