# Generated by Django 4.2.2 on 2023-08-20 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0090_remove_achievementrecord_sport_record_week_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SportRecordWeek',
        ),
    ]
