# Generated by Django 4.2.2 on 2023-08-20 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_sportrecordweek'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievementrecord',
            name='sport_record_week_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='api.sportrecordweek'),
            preserve_default=False,
        ),
    ]
