# Generated by Django 4.2.2 on 2023-08-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0093_achievementrecord_sport_record_week_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievementrecord',
            name='continuous_sport_hundredeighty_week',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='achievementrecord',
            name='continuous_sport_seventyfive_week',
            field=models.IntegerField(default=0),
        ),
    ]
